"use client";
import "../style/index.scss";
import "../style/global.css";

import AppProvider from "@/contextApi/AppProvider";
import ReduxProvider from "@/redux/provider";
import { ToastContainer } from "react-toastify";
import { childrenType } from "@/interFace/interFace";
import { usePathname } from "next/navigation";
import AdminRoute from "@/privetRoute/AdminRoute";
import Sidebar from "@/sheardComponent/Sidebar";
export default function RootLayout({ children }: childrenType) {
  const pathName = usePathname();
  return (
    <>
      <html lang="en">
        <head>
          <meta httpEquiv="x-ua-compatible" content="ie=edge" />
          <meta name="description" content="Generated by create next app" />
          <meta name="robots" content="noindex, follow" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
          />
          <title>ALSTAR Admin</title>
          <link rel="icon" href="/favicon.png" />
          <link
            href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;0,900;1,400;1,600;1,700&display=swap"
            rel="stylesheet"></link>
        </head>

        <body className="bg-bodyBg">
          <AppProvider>
            {pathName === "/login" || pathName === "/register" ? (
              <main>{children}</main>
            ) : (
              <AdminRoute>
                <main>
                  <div className="cashier-dashboard-area">
                    <Sidebar />
                    {children}
                  </div>
                </main>
              </AdminRoute>
            )}
          </AppProvider>
          <ToastContainer />
        </body>
      </html>
    </>
  );
}
